# Form implementation generated from reading ui file 'download_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 148)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img_app/download.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(350, 107, 84, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 333, 135))
        self.groupBox.setObjectName("groupBox")
        self.label_download_info = QtWidgets.QLabel(self.groupBox)
        self.label_download_info.setGeometry(QtCore.QRect(30, 30, 211, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_download_info.setFont(font)
        self.label_download_info.setText("")
        self.label_download_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_download_info.setObjectName("label_download_info")
        self.pushButton_pars_and_download_data = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_pars_and_download_data.setGeometry(QtCore.QRect(245, 85, 85, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pars_and_download_data.setFont(font)
        self.pushButton_pars_and_download_data.setObjectName("pushButton_pars_and_download_data")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(11, 81, 221, 40))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download data"))
        self.pushButton_exit.setText(_translate("MainWindow", "Вихід"))
        self.groupBox.setTitle(_translate("MainWindow", "Інформація про завантаження"))
        self.pushButton_pars_and_download_data.setText(_translate("MainWindow", "Завантажити\n"
"дані"))
