# Form implementation generated from reading ui file 'download_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 151)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img_app/download.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #1E1E1E;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: black;\n"
"    color: yellow;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #2F4F4F;\n"
"    color: #FF0000;\n"
"    border: 1px dashed #000080;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: black;\n"
"    color: #800000;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #FF4500;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    backgrond-color: #696969;\n"
"    color: #7FFF00;\n"
"    border: 1px solid #0000CD;\n"
"}\n"
"\n"
"QProgressBar{\n"
"    border: 1px solid #FF00FF;\n"
"    color: #FFFF00;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar:chunk{\n"
"    background-color: green;\n"
"    width: 6px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 333, 135))
        self.groupBox.setObjectName("groupBox")
        self.label_download_info = QtWidgets.QLabel(parent=self.groupBox)
        self.label_download_info.setGeometry(QtCore.QRect(14, 30, 219, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_download_info.setFont(font)
        self.label_download_info.setText("")
        self.label_download_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_download_info.setObjectName("label_download_info")
        self.pushButton_pars_and_download_data = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_pars_and_download_data.setGeometry(QtCore.QRect(245, 85, 85, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_pars_and_download_data.setFont(font)
        self.pushButton_pars_and_download_data.setObjectName("pushButton_pars_and_download_data")
        self.progressBar = QtWidgets.QProgressBar(parent=self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(11, 87, 227, 37))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_exit.setGeometry(QtCore.QRect(245, 27, 84, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download data"))
        self.groupBox.setTitle(_translate("MainWindow", "Інформація про завантаження"))
        self.pushButton_pars_and_download_data.setText(_translate("MainWindow", "Завантажити\n"
"дані"))
        self.pushButton_exit.setText(_translate("MainWindow", "Повернуться\n"
"на головну"))
