# Form implementation generated from reading ui file 'main_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 345)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img_app/main_app.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #1E1E1E;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: black;\n"
"    color: yellow;\n"
"    border: 1px solid #483D8B;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #2F4F4F;\n"
"    color: #FF0000;\n"
"    border: 1px dashed #000080;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: black;\n"
"    color: #800000;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #FF4500;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    backgrond-color: #696969;\n"
"    color: #7FFF00;\n"
"    border: 1px solid #0000CD;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #DCDCDC;\n"
"    color:     #000080;\n"
"    border: 1px solid #7FFF00; \n"
"}\n"
"QLineEdit:focus{\n"
"    border: 1px dashed #800000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 217, 77))
        self.groupBox.setObjectName("groupBox")
        self.label_info_folder = QtWidgets.QLabel(self.groupBox)
        self.label_info_folder.setGeometry(QtCore.QRect(10, 20, 101, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_info_folder.setFont(font)
        self.label_info_folder.setText("")
        self.label_info_folder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info_folder.setWordWrap(True)
        self.label_info_folder.setObjectName("label_info_folder")
        self.pushButton_download_data = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_download_data.setGeometry(QtCore.QRect(121, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_download_data.setFont(font)
        self.pushButton_download_data.setObjectName("pushButton_download_data")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 342, 200))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_img_charact = QtWidgets.QLabel(self.groupBox_2)
        self.label_img_charact.setGeometry(QtCore.QRect(166, 61, 170, 131))
        self.label_img_charact.setStyleSheet("")
        self.label_img_charact.setText("")
        self.label_img_charact.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_charact.setObjectName("label_img_charact")
        self.label_img_element = QtWidgets.QLabel(self.groupBox_2)
        self.label_img_element.setGeometry(QtCore.QRect(7, 61, 150, 131))
        self.label_img_element.setStyleSheet("")
        self.label_img_element.setText("")
        self.label_img_element.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_element.setObjectName("label_img_element")
        self.pushButton_rand_elem = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_rand_elem.setGeometry(QtCore.QRect(32, 18, 101, 37))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rand_elem.setFont(font)
        self.pushButton_rand_elem.setObjectName("pushButton_rand_elem")
        self.pushButton_rand_charact = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_rand_charact.setGeometry(QtCore.QRect(212, 17, 101, 37))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rand_charact.setFont(font)
        self.pushButton_rand_charact.setObjectName("pushButton_rand_charact")
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_clear.setGeometry(QtCore.QRect(148, 20, 48, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Img_app/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_clear.setIcon(icon1)
        self.pushButton_clear.setIconSize(QtCore.QSize(31, 76))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(253, 54, 59, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_timer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_timer.setGeometry(QtCore.QRect(252, 12, 59, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_timer.setFont(font)
        self.pushButton_timer.setObjectName("pushButton_timer")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 100, 212, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #7FFF00;")
        self.label.setObjectName("label")
        self.lineEdit_last_border_num = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_last_border_num.setGeometry(QtCore.QRect(234, 104, 28, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_last_border_num.setFont(font)
        self.lineEdit_last_border_num.setText("")
        self.lineEdit_last_border_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_last_border_num.setPlaceholderText("")
        self.lineEdit_last_border_num.setObjectName("lineEdit_last_border_num")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(272, 101, 26, 19))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(265, 100, 7, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #7FFF00;")
        self.label_3.setObjectName("label_3")
        self.label_result_rand_num = QtWidgets.QLabel(self.centralwidget)
        self.label_result_rand_num.setGeometry(QtCore.QRect(299, 100, 40, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_result_rand_num.setFont(font)
        self.label_result_rand_num.setStyleSheet("color: #7FFF00;")
        self.label_result_rand_num.setText("")
        self.label_result_rand_num.setObjectName("label_result_rand_num")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random character selection"))
        self.groupBox.setTitle(_translate("MainWindow", "Інформація про папку"))
        self.pushButton_download_data.setText(_translate("MainWindow", "Завантажити\n"
"дані"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Рандомний елемент та персонаж"))
        self.pushButton_rand_elem.setText(_translate("MainWindow", "Зарандомити\n"
"елемент "))
        self.pushButton_rand_charact.setText(_translate("MainWindow", "Зарандомити\n"
"персонажа"))
        self.pushButton_exit.setText(_translate("MainWindow", "Вихід"))
        self.pushButton_timer.setText(_translate("MainWindow", "Таймер"))
        self.label.setText(_translate("MainWindow", "Рандомне число між кордонами (1,"))
        self.label_2.setText(_translate("MainWindow", "= "))
        self.label_3.setText(_translate("MainWindow", ")"))
