# Form implementation generated from reading ui file 'main_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 514)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img_app/main_app.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #1E1E1E;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: black;\n"
"    color: yellow;\n"
"    border: 1px solid #483D8B;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #2F4F4F;\n"
"    color: #FF0000;\n"
"    border: 1px dashed #000080;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: black;\n"
"    color: #800000;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #FF4500;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    backgrond-color: #696969;\n"
"    color: #7FFF00;\n"
"    border: 1px solid #0000CD;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #DCDCDC;\n"
"    color:     #000080;\n"
"    border: 1px solid #7FFF00; \n"
"}\n"
"QLineEdit:focus{\n"
"    border: 1px dashed #800000;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    color: #00FA9A;\n"
"}\n"
"QRadioButton:hover{\n"
"    color: #FF4500;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 217, 77))
        self.groupBox.setObjectName("groupBox")
        self.label_info_folder = QtWidgets.QLabel(parent=self.groupBox)
        self.label_info_folder.setGeometry(QtCore.QRect(10, 20, 101, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_info_folder.setFont(font)
        self.label_info_folder.setText("")
        self.label_info_folder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info_folder.setWordWrap(True)
        self.label_info_folder.setObjectName("label_info_folder")
        self.pushButton_download_data = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_download_data.setGeometry(QtCore.QRect(121, 34, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_download_data.setFont(font)
        self.pushButton_download_data.setObjectName("pushButton_download_data")
        self.pushButton_FAQ_download = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_FAQ_download.setGeometry(QtCore.QRect(175, 4, 37, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_download.setFont(font)
        self.pushButton_FAQ_download.setObjectName("pushButton_FAQ_download")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 342, 285))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_img_charact = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_img_charact.setGeometry(QtCore.QRect(166, 61, 170, 131))
        self.label_img_charact.setStyleSheet("")
        self.label_img_charact.setText("")
        self.label_img_charact.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_charact.setObjectName("label_img_charact")
        self.label_img_element = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_img_element.setGeometry(QtCore.QRect(7, 61, 150, 131))
        self.label_img_element.setStyleSheet("")
        self.label_img_element.setText("")
        self.label_img_element.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_element.setObjectName("label_img_element")
        self.pushButton_rand_elem = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_rand_elem.setGeometry(QtCore.QRect(32, 18, 101, 37))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rand_elem.setFont(font)
        self.pushButton_rand_elem.setObjectName("pushButton_rand_elem")
        self.pushButton_rand_charact = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_rand_charact.setGeometry(QtCore.QRect(212, 17, 101, 37))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rand_charact.setFont(font)
        self.pushButton_rand_charact.setObjectName("pushButton_rand_charact")
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_clear.setGeometry(QtCore.QRect(148, 20, 48, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Img_app/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_clear.setIcon(icon1)
        self.pushButton_clear.setIconSize(QtCore.QSize(31, 76))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_name_charact = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_name_charact.setGeometry(QtCore.QRect(166, 197, 170, 83))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_name_charact.setFont(font)
        self.label_name_charact.setStyleSheet("color: #ADFF2F")
        self.label_name_charact.setText("")
        self.label_name_charact.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_name_charact.setWordWrap(True)
        self.label_name_charact.setObjectName("label_name_charact")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(253, 54, 59, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_timer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_timer.setGeometry(QtCore.QRect(252, 12, 59, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_timer.setFont(font)
        self.pushButton_timer.setObjectName("pushButton_timer")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(7, 180, 733, 330))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_rand_squad = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_rand_squad.setGeometry(QtCore.QRect(20, 20, 101, 37))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_rand_squad.setFont(font)
        self.pushButton_rand_squad.setObjectName("pushButton_rand_squad")
        self.pushButton_clear_2 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_clear_2.setGeometry(QtCore.QRect(150, 22, 48, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_clear_2.setFont(font)
        self.pushButton_clear_2.setText("")
        self.pushButton_clear_2.setIcon(icon1)
        self.pushButton_clear_2.setIconSize(QtCore.QSize(31, 76))
        self.pushButton_clear_2.setObjectName("pushButton_clear_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 70, 90, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ADFF2F")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(380, 70, 90, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #ADFF2F")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_img_charact_squad_1 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_img_charact_squad_1.setGeometry(QtCore.QRect(9, 105, 170, 131))
        self.label_img_charact_squad_1.setStyleSheet("")
        self.label_img_charact_squad_1.setText("")
        self.label_img_charact_squad_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_charact_squad_1.setObjectName("label_img_charact_squad_1")
        self.label_img_charact_squad_2 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_img_charact_squad_2.setGeometry(QtCore.QRect(187, 105, 170, 131))
        self.label_img_charact_squad_2.setStyleSheet("")
        self.label_img_charact_squad_2.setText("")
        self.label_img_charact_squad_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_charact_squad_2.setObjectName("label_img_charact_squad_2")
        self.label_img_charact_squad_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_img_charact_squad_3.setGeometry(QtCore.QRect(379, 105, 170, 131))
        self.label_img_charact_squad_3.setStyleSheet("")
        self.label_img_charact_squad_3.setText("")
        self.label_img_charact_squad_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_charact_squad_3.setObjectName("label_img_charact_squad_3")
        self.label_img_charact_squad_4 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_img_charact_squad_4.setGeometry(QtCore.QRect(557, 105, 170, 131))
        self.label_img_charact_squad_4.setStyleSheet("")
        self.label_img_charact_squad_4.setText("")
        self.label_img_charact_squad_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_charact_squad_4.setObjectName("label_img_charact_squad_4")
        self.label_name_charact_squad_1 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_name_charact_squad_1.setGeometry(QtCore.QRect(9, 240, 170, 83))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_name_charact_squad_1.setFont(font)
        self.label_name_charact_squad_1.setStyleSheet("color: #ADFF2F")
        self.label_name_charact_squad_1.setText("")
        self.label_name_charact_squad_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_name_charact_squad_1.setWordWrap(True)
        self.label_name_charact_squad_1.setObjectName("label_name_charact_squad_1")
        self.label_name_charact_squad_2 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_name_charact_squad_2.setGeometry(QtCore.QRect(187, 241, 170, 83))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_name_charact_squad_2.setFont(font)
        self.label_name_charact_squad_2.setStyleSheet("color: #ADFF2F")
        self.label_name_charact_squad_2.setText("")
        self.label_name_charact_squad_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_name_charact_squad_2.setWordWrap(True)
        self.label_name_charact_squad_2.setObjectName("label_name_charact_squad_2")
        self.label_name_charact_squad_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_name_charact_squad_3.setGeometry(QtCore.QRect(379, 241, 170, 83))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_name_charact_squad_3.setFont(font)
        self.label_name_charact_squad_3.setStyleSheet("color: #ADFF2F")
        self.label_name_charact_squad_3.setText("")
        self.label_name_charact_squad_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_name_charact_squad_3.setWordWrap(True)
        self.label_name_charact_squad_3.setObjectName("label_name_charact_squad_3")
        self.label_name_charact_squad_4 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_name_charact_squad_4.setGeometry(QtCore.QRect(558, 241, 170, 83))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_name_charact_squad_4.setFont(font)
        self.label_name_charact_squad_4.setStyleSheet("color: #ADFF2F")
        self.label_name_charact_squad_4.setText("")
        self.label_name_charact_squad_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_name_charact_squad_4.setWordWrap(True)
        self.label_name_charact_squad_4.setObjectName("label_name_charact_squad_4")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 90, 216, 83))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_rand_squad = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButton_rand_squad.setGeometry(QtCore.QRect(7, 47, 179, 33))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_rand_squad.setFont(font)
        self.radioButton_rand_squad.setCheckable(True)
        self.radioButton_rand_squad.setChecked(False)
        self.radioButton_rand_squad.setObjectName("radioButton_rand_squad")
        self.radioButton_rand_elem_charact = QtWidgets.QRadioButton(parent=self.groupBox_4)
        self.radioButton_rand_elem_charact.setGeometry(QtCore.QRect(7, 5, 179, 33))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_rand_elem_charact.setFont(font)
        self.radioButton_rand_elem_charact.setCheckable(True)
        self.radioButton_rand_elem_charact.setChecked(True)
        self.radioButton_rand_elem_charact.setObjectName("radioButton_rand_elem_charact")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random character selection"))
        self.groupBox.setTitle(_translate("MainWindow", "Інформація про папку"))
        self.pushButton_download_data.setText(_translate("MainWindow", "Завантажити\n"
"дані"))
        self.pushButton_FAQ_download.setText(_translate("MainWindow", "?"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Рандомний елемент та персонаж"))
        self.pushButton_rand_elem.setText(_translate("MainWindow", "Зарандомити\n"
"елемент "))
        self.pushButton_rand_charact.setText(_translate("MainWindow", "Зарандомити\n"
"персонажа"))
        self.pushButton_exit.setText(_translate("MainWindow", "Вихід"))
        self.pushButton_timer.setText(_translate("MainWindow", "Таймер"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Рандомний вибір персонажів для коопа"))
        self.pushButton_rand_squad.setText(_translate("MainWindow", "Зарандомити\n"
"персонажів"))
        self.label.setText(_translate("MainWindow", "1 гравець"))
        self.label_2.setText(_translate("MainWindow", "2 гравець"))
        self.radioButton_rand_squad.setText(_translate("MainWindow", "Зарандомити персонажів\n"
"для коопу"))
        self.radioButton_rand_elem_charact.setText(_translate("MainWindow", "Зарандомити один\n"
"елемент і персонажа"))
